// CS Executive Module 2 (Group 2) — lesson data
// Source: official ICSI syllabus + lesson-wise summaries in each paper's study material.
// "notes" are starter summaries — expand any lesson by asking the bot or editing here.

const PAPERS = {
  cmsl: {
    id: "cmsl",
    code: "Paper 5",
    title: "Capital Market & Securities Laws",
    short: "CMSL",
    parts: [
      { name: "Part I — Capital Market", marks: 40 },
      { name: "Part II — Securities Laws", marks: 60 },
    ],
    lessons: [
      { n: 1, part: 0, title: "Basics of Capital Market", notes: "Covers the structure of the capital market, its participants (issuers, investors, intermediaries), and capital market instruments. Foundation lesson — savings → investment → capital formation chain." },
      { n: 2, part: 0, title: "Secondary Market in India", notes: "Development of the Indian stock market, trading mechanism, Exchange Traded Funds, derivatives, rights entitlements, block/bulk deals, Sensex & Nifty basics, types of indexes, clearing corporations, and secondary-market regulators." },
      { n: 3, part: 0, title: "Securities Contracts (Regulation) Act, 1956", notes: "SCRA regulates stock exchanges and securities contracts; in force since 20 Feb 1957. Covers powers of the Central Government, SEBI's delegated powers, penal provisions, offences and procedures." },
      { n: 4, part: 0, title: "Securities and Exchange Board of India", notes: "SEBI's powers and functions, penalties and adjudication, the Securities Appellate Tribunal (SAT), Central Government powers, the SCORES grievance framework, and the Informal Guidance Scheme." },
      { n: 5, part: 0, title: "Laws Governing Depositories and Depository Participants", notes: "A Depository holds securities in electronic (dematerialised) form on an investor's behalf via a Depository Participant (DP) — a bank, financial institution or SEBI-eligible broker." },
      { n: 6, part: 0, title: "Securities Market Intermediaries", notes: "Types and roles of market intermediaries in the primary and secondary markets, SEBI's regulatory oversight, inspection powers, fee collection and penalty powers over intermediaries." },
      { n: 7, part: 0, title: "International Financial Services Centres Authority (IFSCA)", notes: "Establishment, powers and functions of IFSCA; concept of an International Financial Services Centre (IFSC); financial products/services; listing & trading of units in an IFSC; SEBI IFSC Guidelines." },
      { n: 8, part: 1, title: "Issue of Capital & Disclosure Requirements", notes: "Types of issues — IPO, FPO, Rights Issue, Preferential Issue, QIP, IPO/Rights Issue of Indian Depository Receipts, SME IPOs, Bonus Issue." },
      { n: 9, part: 1, title: "Share Based Employee Benefits and Sweat Equity", notes: "SEBI (Share Based Employee Benefits and Sweat Equity) Regulations, 2021 — replaced the 2002/2014 regulations. Scheme implementation, ESOS/ESPS administration, sweat equity issuance, pricing, accounting treatment, lock-in and listing." },
      { n: 10, part: 1, title: "Issue and Listing of Non-Convertible Securities", notes: "Framework for debt securities and non-convertible/redeemable preference shares — issue and listing requirements." },
      { n: 11, part: 1, title: "Listing Obligations and Disclosure Requirements (LODR)", notes: "Key provisions of SEBI (LODR) Regulations, 2015 — corporate governance obligations, disclosure requirements, board committees, vigil mechanism, related party transactions, and the Company Secretary's role as compliance officer." },
      { n: 12, part: 1, title: "Acquisition of Shares and Takeovers — Concepts", notes: "Acquisition as a mode of corporate expansion; SAST (Substantial Acquisition of Shares and Takeovers) Regulations concepts — open offers, triggers, exemptions." },
      { n: 13, part: 1, title: "Prohibition of Insider Trading", notes: "Key definitions — connected person, deemed connected person, insider, unpublished price sensitive information (UPSI); restrictions on communicating/procuring UPSI; trading plans; disclosure requirements; code of fair disclosure and conduct; penalties." },
      { n: 14, part: 1, title: "Prohibition of Fraudulent and Unfair Trade Practices", notes: "SEBI (PFUTP) Regulations, 2003 — empowers SEBI to investigate market manipulation and fraudulent/unfair trade practices in the securities market." },
      { n: 15, part: 1, title: "Delisting of Equity Shares", notes: "Framework and process for voluntary and compulsory delisting of equity shares from stock exchanges." },
      { n: 16, part: 1, title: "Buy-Back of Securities", notes: "Buy-back as a capital restructuring strategy — raising EPS, averting hostile takeovers, improving stakeholder returns. Introduced via Companies (Amendment) Act, 1999 (Sections 77A/77AA/77B); SEBI Buy-Back Regulations." },
      { n: 17, part: 1, title: "Mutual Funds", notes: "Structure, regulation and operation of mutual funds under SEBI (Mutual Funds) Regulations." },
      { n: 18, part: 1, title: "Collective Investment Schemes", notes: "Regulatory framework governing Collective Investment Schemes (CIS) under SEBI regulations." },
    ],
  },

  ecip: {
    id: "ecip",
    code: "Paper 6",
    title: "Economic, Commercial & Intellectual Property Laws",
    short: "ECIP",
    parts: [
      { name: "Part I — Economic & Commercial Laws", marks: 60 },
      { name: "Part II — Intellectual Property Laws", marks: 40 },
    ],
    lessons: [
      { n: 1, part: 0, title: "Law relating to Foreign Exchange Management", notes: "FEMA, 1999 consolidates and amends foreign exchange law to facilitate external trade/payments and orderly development of India's forex market. Covers current & capital account transactions, Liberalised Remittance Scheme, acquisition/transfer of immovable property in India, export of goods/services, realisation & repatriation, and RBI's role." },
      { n: 2, part: 0, title: "Foreign Direct Investments — Regulations & Policy", notes: "Automatic Route vs Approval Route of FDI, prohibited/permitted sectors, conditions in key sectors (e-commerce, insurance), modes of payment, reporting of FDI (FC-GPR and other returns)." },
      { n: 3, part: 0, title: "Overseas Direct Investment (ODI)", notes: "Overseas investment = financial commitment + overseas portfolio investment by a person resident in India. Enables Indian entrepreneurs to access global markets, technology and capital." },
      { n: 4, part: 0, title: "Foreign Trade Policy & Procedure", notes: "Framework governing India's foreign trade policy and related procedural compliance." },
      { n: 5, part: 0, title: "Law relating to Special Economic Zones", notes: "SEZ Act, 2005 — establishment, development and management of SEZs to promote exports; SEZ Rules, 2006 authorise Company Secretaries to appear before the Board of Approval. Covers establishment, approval/authorisation to operate, unit setup, and the SEZ Authority." },
      { n: 6, part: 0, title: "Law relating to Foreign Contribution Regulation", notes: "Regulatory framework for foreign contributions (FCRA) — registration, compliance and restrictions on receiving foreign contributions." },
      { n: 7, part: 0, title: "Prevention of Money Laundering", notes: "PMLA — offence of money laundering, attachment/adjudication/confiscation, obligations of banking companies/financial institutions/intermediaries, role of the Enforcement Directorate, KYC and FIU concepts." },
      { n: 8, part: 0, title: "Competition Law", notes: "Competition Act, 2002 — establishes the Competition Commission to prevent practices with an adverse effect on competition, promote/sustain competition, protect consumer interests, and ensure freedom of trade." },
      { n: 9, part: 0, title: "Law relating to Consumer Protection", notes: "Consumer protection framework in India — rights of consumers, Consumer Dispute Redressal Forums, nature/scope of remedies, e-commerce and direct-selling guidelines." },
      { n: 10, part: 0, title: "Legal Metrology", notes: "Legal Metrology Act, 2009 — standards of weights and measures, power of inspection and seizure, declarations on pre-packaged commodities, offences and penalties." },
      { n: 11, part: 0, title: "Real Estate Regulation and Development Law", notes: "RERA, 2016 — protects consumer rights and promotes uniformity/standardisation in real estate. Covers project registration, real estate agents, the Real Estate Regulatory Authority, Central Advisory Council, Appellate Tribunal, and penalties." },
      { n: 12, part: 1, title: "Intellectual Property Rights — Overview", notes: "International IPR framework — GATS, WIPO, TRIPS, international conventions; India's National IPR Policy, its coverage and goals." },
      { n: 13, part: 1, title: "Law relating to Patents", notes: "Patents promote innovation and give the patentee a monopoly to commercially exploit an invention. Covers applications, publication & examination of applications, inventions not patentable, and opposition proceedings." },
      { n: 14, part: 1, title: "Law relating to Trade Marks", notes: "Trade mark registration, rights conferred, infringement and passing off, and related procedural aspects." },
      { n: 15, part: 1, title: "Law relating to Copyright", notes: "Copyright — key concepts (adaptations, author, subsistence of copyright), object/purpose/scope of Indian copyright law, meaning, term, assignment, infringement, registration and licensing." },
      { n: 16, part: 1, title: "Law relating to Geographical Indications of Goods", notes: "GI law protects region-specific reputation built up over time — registration, protection and enforcement of Geographical Indications." },
      { n: 17, part: 1, title: "Law relating to Designs", notes: "Design law — registration, protection and infringement relating to industrial designs." },
    ],
  },

  tax: {
    id: "tax",
    code: "Paper 7",
    title: "Tax Laws & Practice",
    short: "TAX",
    parts: [
      { name: "Part I — Direct Tax", marks: 60 },
      { name: "Part II — Indirect Tax (GST & Customs)", marks: 40 },
    ],
    lessons: [
      { n: 1, part: 0, title: "Direct Taxes — At a Glance", notes: "Introduction to taxation — characteristics and objectives of taxes, direct vs indirect tax, background of India's taxation system, tax structure & administration (CBDT, Income Tax Department, CBIC, GST Council)." },
      { n: 2, part: 0, title: "Basic Concept of Income Tax", notes: "Overview of the Finance Bill, key definitions, capital vs revenue receipts/expenditure, residential status (Section 6) for individuals/HUF/firms/companies, POEM, scope of total income (Section 5), charge of income tax (Section 4)." },
      { n: 3, part: 0, title: "Incomes which do not form part of Total Income", notes: "Section 10 exemptions — income not charged to tax (e.g. scholarships). Distinguished from deductions, which reduce taxable income after inclusion (e.g. Section 80G)." },
      { n: 4, part: 0, title: "Income under the head Salary", notes: "Computation of income chargeable under the head 'Salary' — components, exemptions and deductions specific to salary income." },
      { n: 5, part: 0, title: "Income under the head House Property", notes: "Computation of income from house property — annual value, deductions under Section 24, treatment of self-occupied vs let-out property." },
      { n: 6, part: 0, title: "Profits and Gains from Business and Profession", notes: "Computation of income under the head 'Profits and Gains of Business or Profession' — allowable/disallowable expenses, depreciation and related provisions." },
      { n: 7, part: 0, title: "Capital Gains", notes: "Fourth head of income — gain on transfer of a capital asset. Classified as Short Term vs Long Term Capital Gains; computation provisions for each." },
      { n: 8, part: 0, title: "Income from Other Sources", notes: "The residuary head of income — covers income not chargeable under any other head and not excluded from total income." },
      { n: 9, part: 0, title: "Clubbing Provisions and Set Off / Carry Forward of Losses", notes: "Clubbing of another person's income into the assessee's total income in specified cases; rules for setting off losses against income and carrying forward unabsorbed losses." },
      { n: 10, part: 0, title: "Deductions", notes: "Deductions under Chapter VIA (Sections 80C to 80U) — reduce Gross Total Income to arrive at Total Income." },
      { n: 11, part: 0, title: "Computation of Total Income and Tax Liability of Various Entities", notes: "Full computation format: Salary + House Property + Business/Profession + Capital Gains + Other Sources, adjusted for clubbing and set-off, minus Chapter VIA deductions = Total Income. Covers individuals, HUFs, firms, AOPs/BOIs and co-operative societies." },
      { n: 12, part: 0, title: "Classification and Tax Incidence on Companies", notes: "Tax treatment specific to companies — classification and incidence of tax on corporate entities." },
      { n: 13, part: 0, title: "Procedural Compliance", notes: "TDS and TCS provisions (with emphasis on e-TDS), Advance Tax & Self-Assessment Tax (SAT), filing of returns, fees/interest for default in furnishing returns." },
      { n: 14, part: 1, title: "Concept of Indirect Taxes at a Glance", notes: "Constitutional powers of taxation, overview of indirect taxes in India, pre-GST tax structure and its shortcomings, administration of indirect taxation pre- and post-GST." },
      { n: 15, part: 1, title: "Basics of Goods and Services Tax (GST)", notes: "Basic concepts and overview of GST; the CGST/IGST/SGST/UTGST model; GST compensation to states." },
      { n: 16, part: 1, title: "Levy and Collection of GST", notes: "Taxable event, concept of supply (including composite and mixed supply), levy & collection of CGST/IGST, exemptions. Reverse Charge Mechanism — liability shifts to the recipient instead of the supplier." },
      { n: 17, part: 1, title: "Time, Value & Place of Supply", notes: "Time of Supply determines the point of levy; Value of Supply determines the taxable value (per GST valuation rules); Place of Supply determines whether a transaction is inter-state, intra-state, import or export." },
      { n: 18, part: 1, title: "Input Tax Credit & Computation of GST Liability", notes: "Rules for claiming Input Tax Credit (ITC) and computing net GST liability after adjusting ITC against output tax." },
      { n: 19, part: 1, title: "Procedural Compliance under GST", notes: "Registration, invoicing, returns filing and other procedural requirements under GST law." },
      { n: 20, part: 1, title: "Overview of Customs Act", notes: "Introduction to the Customs Act — levy of customs duty on import/export of goods, basic concepts and administration." },
    ],
  },
};
